# Generated by Django 4.0.4 on 2022-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('storage', models.JSONField(null=True)),
                ('ram', models.JSONField(null=True)),
                ('cpu', models.JSONField(null=True)),
                ('gpu', models.JSONField(null=True)),
                ('display', models.CharField(default='24"', max_length=200)),
                ('OS', models.CharField(default='Ubuntu', max_length=200)),
                ('soundCard', models.CharField(default='Yes', max_length=200)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('storage', models.JSONField(null=True)),
                ('ram', models.JSONField(null=True)),
                ('cpu', models.JSONField(null=True)),
                ('display', models.CharField(default='13"', max_length=200)),
                ('OS', models.CharField(default='Ubuntu', max_length=200)),
                ('soundCard', models.CharField(default='Yes', max_length=200)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
