# Generated by Django 4.0.4 on 2022-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0005_alter_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='a@b.com', max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
